### ISSUE TITLE
HPOS does not receive TLS certificate

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-nixpkgs#370] opened 2020-02-05 16:07 UTC
Reported here: https://www.pivotaltracker.com/story/show/170923638

During QA of `staging` on both HoloPorts and VMs, hpstatus page does not redirect to HP admin. This appears to be because the HoloPort never receives a TLS certificate:
- HoloPort does successfully register itself on ZT
- Have confirmed that hpstatus.holo.host is regularly checking <holoportid>.holohost.net
- On Safari the error message is explicitly: `Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made`
- Going directly to the HoloPort URL yields a security warning. 

**Ignoring security warning leads to 403 error NOT HP Admin page as expected**

Video attached: https://drive.google.com/open?id=13stZSx_JpcsblMP4ecCpCjgmhTooyaz4

This has been replaced multiple times by Mary and Joel on HoloPorts, and Alastair on VM

CC: @yegortimoshenko

**Comment by yegortimoshenko** [comment] 2020-02-05 16:37
I wonder if it could be that reporter is hitting one of Let's Encrypt rate limits: https://letsencrypt.org/docs/rate-limits/

> Renewals are treated specially: they don’t count against your Certificates per Registered Domain limit, but they are subject to a Duplicate Certificate limit of 5 per week.

(This means that the same `hpos-config.json` can only have certs issued for it 5 times per week.)

> There is a Failed Validation limit of 5 failures per account, per hostname, per hour. 

> You can create a maximum of 10 Accounts per IP Address per 3 hours.

**Comment by yegortimoshenko** [comment] 2020-02-05 16:38
Best way to ensure that isn't happening is to generate a new `hpos-config.json` and try a different IP address (VPN, or different internet connection, or different person).

**Comment by alastairong** [comment] 2020-02-05 16:40
These were all done with new `hpos-config.json`. I didn't get this error using old `hpos-config.json` files presumably because HoloPort URL was the same as an old one and therefore the cert already existed?

I think I tried different IP addresses too (I tested this in two different locations).

**Comment by yegortimoshenko** [comment] 2020-02-05 16:40
Could you send `journalctl -u acme-default` output?

**Comment by alastairong** [comment] 2020-02-05 16:43
Will get these and upload here.

**Comment by alastairong** [comment] 2020-02-05 17:28
So turns out I don't know how to download logs from a VM...

Here's a screenshot of my log. Doesn't look like ACME-default is doing much. I'll add other logs as I get them.

<img width="638" alt="Screenshot 2020-02-05 at 17 27 07" src="https://user-images.githubusercontent.com/16625137/73866434-c0511b80-483c-11ea-8cc3-9693f490ab35.png">

**Comment by yegortimoshenko** [comment] 2020-02-05 18:52
What is your VM's IP address? We'll need to sync up and test this in real time.

**Comment by yegortimoshenko** [comment] 2020-02-05 18:52
This looks like you're running into ZeroTier VM connectivity issue I talked about earlier.

**Comment by alastairong** [comment] 2020-02-06 10:40
Interesting. Well if my VM is an issue my suggestion is to sync up with Joel and/or Mary instead as he has encountered the same issue on a real HoloPort. But let's wait to get those logs to confirm it's the same issue.

**Comment by alastairong** [comment] 2020-02-06 12:06
Here are Mary's logs for a real HoloPort. HoloPort has been able to successfully register on `master` before and has gone through factory reset for this process.

Sorry that we only have photos XD

![IMG_20200206_125243](https://user-images.githubusercontent.com/16625137/73935722-1a072380-48d9-11ea-8dee-8d84f21c35be.jpg)
![IMG_20200206_125300](https://user-images.githubusercontent.com/16625137/73935728-1c697d80-48d9-11ea-8673-eace34b77fe2.jpg)

**Comment by zo-el** [comment] 2020-02-06 18:36
#### Here are my logs:
`Log 1` shows the general logs (`journalctl -f`), 
> Note the bottom logs in the image for `Log 1`
![Log 1](https://user-images.githubusercontent.com/29548571/73967254-27bea800-48dd-11ea-9148-ad5f31a9fc6d.jpeg)

`Log 2` is what I receive when I run `journalctl -u acme-default`
![Log 2](https://user-images.githubusercontent.com/29548571/73967253-27261180-48dd-11ea-8e9a-515bb6f351e6.jpeg)

**Comment by marycamacho** [comment] 2020-02-07 10:58
If downloaded logs are necessary today, I can provide those. I am available to cowork and reproduce any issues on a HoloPort - also, I have a fresh HP+ that has previously been registered on master, but that I have switched to the staging channel but have not registered on the network yet.

**Comment by alastairong** [comment] 2020-02-07 11:33
Me too :)

CC: @yegortimoshenko

**Comment by yegortimoshenko** [comment] 2020-02-07 13:35
Thank you for connecting @alastairong. Resolved in #370.

**Closed by yegortimoshenko** 2020-02-07 13:35 UTC
Labels: Bug, Project: HoloPortOS

**Comment by peeech** [comment] 2020-02-07 13:42
@yegortimoshenko did you mean #373?

**Comment by yegortimoshenko** [comment] 2020-02-07 13:43
Hah, it was circular :) I meant #373.

**Comment by alastairong** [comment] 2020-02-07 14:29
Confirming that I have tested this and it worked fine. Redirected after 1.5 minutes
